/****** Object:  Database [sfcontractservice_db]    Script Date: 11/5/2018 4:35:23 PM ******/
CREATE DATABASE [sfcontractservice_db]  (EDITION = 'Standard', SERVICE_OBJECTIVE = 'S0', MAXSIZE = 1 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [sfcontractservice_db] SET COMPATIBILITY_LEVEL = 140
GO

ALTER DATABASE [sfcontractservice_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sfcontractservice_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sfcontractservice_db] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [sfcontractservice_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sfcontractservice_db] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [sfcontractservice_db] SET  MULTI_USER 
GO

ALTER DATABASE [sfcontractservice_db] SET ENCRYPTION ON
GO

ALTER DATABASE [sfcontractservice_db] SET QUERY_STORE = ON
GO

ALTER DATABASE [sfcontractservice_db] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

ALTER DATABASE [sfcontractservice_db] SET  READ_WRITE 
GO

